data_dirs:
  - /media/diego/QData/bankdomain/docs/bankdomain/qa_documents
  - /media/diego/QData/bankdomain/docs/insurancedomain/qa_documents

mongo_connection: mongodb://localhost:27017
corpus_dir: /media/diego/QData/bankdomain/corpus
output_dir: /media/diego/QData/bankdomain/data
corpus_filename: qa_questions.corpus
corpus_proc_filename: proc_questions.corpus
corpus_mod_filename: mod_questions.corpus
models_dir: /media/diego/QData/bankdomain/model/
dump_dir: /media/diego/QData/bankdomain/dump/
key_file: /media/diego/keys/db_coords.yml
preload_words : False
