CUSTOM_REMOVES = ["Abkommen", "deutsch", "reichen"]

CUSTOM_LOOKUP = {
    "Abbuchungen" : "Abbuchung",
    "Abrechnungskontos" : "Abrechnungskonto",
    "Abrechnungskonten": "Abrechnungskonto",
    "Abwicklungskontos" : "Abwicklungskonto",
    "Abwicklungskonten" : "Abwicklungskonto",
    "Adresszusatzes" : "Adresszusatz",
    "Adresszusätze": "Adresszusatz",
    "Aktivierungscodes" : "Aktivierungscode",
    "angebotenes" : "angeboten",
    "angebotene": "angeboten",
    "angebotener": "angeboten",
    "angebotenen": "angeboten",
    "angebotenem": "angeboten",
    "Anlageentscheidungen" : "Anlageentscheidung",
    "Anlagekontos" : "Anlagekonto",
    "Anlagekonten": "Anlagekonto",
    "Anlagebetrages" : "Anlagebetrag",
    "Anmeldenamen" : "Anmeldename",
    "Arbeitsvertrages" : "Arbeitsvertrag",
    "Apps" : "App",
    "Arbeitstage" : "Arbeitstag",
    "Arbeitstagen": "Arbeitstag",
    "Arbeitstages" : "Arbeitstag",
    "Auslandszahlungen" : "Auslandszahlung",
    "Auszahlungskontos" : "Auszahlungskonto",
    "Auszahlungskonten" : "Auszahlungskonto",
    "Auslandsüberweisungen": "Auslandsüberweisung",
    "angeboten" : "anbieten",
    "Anlagebetrage" : "Anlagebetrag",
    "Anlagebetrages" : "Anlagebetrag",
    "Antrages" : "Antrag",
    "Aufträge"  : "Auftrag",
    "Aufträge": "Auftrag",
    "Auslandsschecks" : "Auslandsscheck",
    "ausgänge" : "ausgang",
    "Bankgeschäftstages" : "Bankgeschäftstag",
    "Bankkonten": "Bankkonto",
    "Bankkontos" : "Bankkonto",
    "Bareinzahlungen" : "Bareinzahlung",
    "Bargeldverfügungen" : "Bargeldverfügung",
    "Basisgirokontos" : "Basisgirokonto",
    "Basisgirokonten": "Basisgirokonto",
    "Basiskontos" : "Basiskonto",
    "Basiskonten": "Basiskonto",
    "Bausparkassen" : "Bausparkasse",
    "Bausparvertrags" : "Bausparvertrag",
    "Bausparverträge": "Bausparvertrag",
    "Bausparvertrages" : "Bausparvertrag",
    "Bauzinsen" : "Bauzins",
    "Bauzinse": "Bauzins",
    "Bauzinses": "Bauzins",
    "Bearbeitungsgebühren" : "Bearbeitungsgebühr",
    "Benachrichtigungen" : "Benachrichtigung",
    "Beratungscentern" : "Beratungscenter",
    "Beratungscenters": "Beratungscenter",
    "Beratungsstellen" : "Beratungsstelle",
    "Bestandskunden" :"Bestandskunde",
    "Betragsaufstockungen" : "Betragsaufstockung",
    "Betriebsmittelkredite" : "Betriebsmittelkredit",
    "Betriebsmittelkrediten": "Betriebsmittelkredit",
    "Betriebssystemen" : "Betriebssystem",
    "Betriebssystems": "Betriebssystem",
    "Betriebssysteme": "Betriebssystem",

    "Bezahlvorganges" : "Bezahlvorgang",
    "Bezahlvorgangs" : "Bezahlvorgang",
    "Bezahlvorgänge": "Bezahlvorgang",
    "Bezahlvorgängen": "Bezahlvorgang",

    "bluetoothTAN-Verfahrens" : "bluetoothTAN-Verfahren",
    "bonitätsabhängigen": "bonitätsabhängig",
    "bonitätsabhängiger": "bonitätsabhängig",
    "bonitätsabhängiges": "bonitätsabhängig",
    "bonitätsabhängige": "bonitätsabhängig",
    "bonitätsunabhängigen" : "bonitätsunabhängig",
    "bonitätsunabhängiger": "bonitätsunabhängig",
    "bonitätsunabhängiges": "bonitätsunabhängig",
    "bonitätsunabhängige": "bonitätsunabhängig",

    "Bonitätsauskünfte" : "Bonitätsauskunft",
    "Bonitätsauskunftes": "Bonitätsauskunft",

    "Bereitstellungszinsen" : "Bereitstellungszins",
    "Browsers" : "Browser",
    "Buchungen" : "Buchung",
    "Buttons" : "Button",

    "Cards": "Card",
    "cards": "Card",
    "chipTAN-Verfahrens" : "chipTAN-Verfahren",
    "Darlehensbeträgen" : "Darlehensbetrag",
    "Darlehensbeträge": "Darlehensbetrag",
    "Darlehensbetrags": "Darlehensbetrag",

    "Darlehenszinsen": "Darlehenszins",
    "Darlehenszinse": "Darlehenszins",
    "Darlehenszinses": "Darlehenszins",
    "Darlehensvertrages" : "Darlehensvertrag",
    "Darlehensverträge": "Darlehensvertrag",
    "Darlehensverträgen": "Darlehensvertrag",
    "Datensätze": "Datensatz",
    "Datensätzen": "Datensatz",
    "Datensatzes": "Datensatz",
    "Daueraufträge" : "Dauerauftrag",
    "Daueraufträgen": "Dauerauftrag",
    "Dauerauftrages" : "Dauerauftrag",
    "Dauerauftrags": "Dauerauftrag",
    "Depotgebühren" : "Depotgebühr",
    "Depots" : "Depot",
    "Dividendenzahlungen" : "Dividendenzahlung",
    "Dienstleistungen" : "Dienstleistung",
    "Dispokredites" : "Dispokredit",
    "Dispokredite": "Dispokredit",
    "Dispokredits": "Dispokredit",
    "Dispokrediten": "Dispokredit",
    "Disporahmens": "Disporahmen",
    "Dispozinsen" : "Dispozins",
    "Dispozinse": "Dispozins",
    "Dispozinses": "Dispozins",
    "Drittanbietern" : "Drittanbieter",
    "Eingabefelder" : "Eingabefeld",
    "Eingabefeldern": "Eingabefeld",

    "eingeräumt" : "einräumen",
    "eTAN-Verfahrens" : "eTAN-Verfahren",
    "Effektivzinsen": "Effektivzins",
    "Effektivzinses": "Effektivzins",
    "Effektivzinse": "Effektivzins",

    "Eigenkapitals" : "Eigenkapital",
    "Einkaufbetrages" : "Einkaufbetrag",
    "Einkaufbetrags" : "Einkaufbetrag",
    "Einkaufsvorganges": "Einkaufsvorgang",
    "Einkaufsvorgangs": "Einkaufsvorgang",
    "Einkaufsvorgänge": "Einkaufsvorgang",
    "Einkaufsvorgängen": "Einkaufsvorgang",
    "Einlagensicherungssysteme" : "Einlagensicherungssystem",
    "Einlagensicherungssystemen": "Einlagensicherungssystem",

    "Einzelhändlern" : "Einzelhändler",
    "Einzelverträge" : "Einzelvertrag",
    "Einzelverträgen": "Einzelvertrag",
    "Einzelvertrages": "Einzelvertrag",

    "Empfängerkontos" : "Empfängerkonto",
    "Empfängerkonten": "Empfängerkonto",
    "Entschädigungszahlungen" :"Entschädigungszahlung",
    "Erbscheines" : "Erbschein",
    "Erkanntes" : "erkannt",
    "Erkannter": "erkannt",
    "erneute": "erneut",
    "erneuten": "erneut",
    "erneutes": "erneut",
    "erneuter": "erneut",
    "erneutem": "erneut",
    "ETFs" : "ETF",
    "EURO-Überweisungen" : "EURO-Überweisung",
    "Fallen" : "fallen",
    "Fällt" : "fallen",
    "Fehlversuche" : "Fehlversuch",
    "Fehlversuchen": "Fehlversuch",
    "Feiertage": "Feiertag",
    "Feiertagen": "Feiertag",
    "Feiertages": "Feiertag",
    "Firmenkunden" : "Firmenkunde",
    "FlatKontos" : "FlatKonto",
    "FlatKonten": "FlatKonto",
    "Festgeldanlagen " : "Festgeldanlage",
    "Festgeldkontos" : "Festgeldkonto",
    "Festgeldkonten" : "Festgeldkonto",
    "Festgeld-Kontos" : "Festgeldkonto",
    "Festgeld-Konten" : "Festgeldkonto",
    "Festgeld-Konto": "Festgeldkonto",
    "Filialbanken" : "Filialbank",
    "Finanzassistenten" : "Finanzassistent",
    "Finanzassistente": "Finanzassistent",
    "Finanzmärkten" : "Finanzmarkt",
    "Finanzmärkte": "Finanzmarkt",
    "Finanzmarktes": "Finanzmarkt",

    "Finanzinstitute": "Finanzinstitut",
    "Finanzinstituts": "Finanzinstitut",

    "Finanzinstituten" : "Finanzinstitut",
    "Folgejahres" : "Folgejahr",
    "Folgejahre": "Folgejahr",
    "Folgemonates" : "Folgemonat",
    "Folgemonate": "Folgemonat",
    "Folgemonats": "Folgemonat",
    "Förderkredite" : "Förderkredit",
    "Förderkredits" : "Förderkredit",
    "Förderungen" : "Förderung",

    "Förderkrediten": "Förderkredit",
    "Frage" : "fragen",
    "Freistellungsauftrags" : "Freistellungsauftrag",
    "Freistellungsauftrages": "Freistellungsauftrag",
    "Freistellungsaufträge" : "Freistellungsauftrag",
    "Freistellungsaufträgen" : "Freistellungsauftrag",
    "freizuschalten" : "freischalten",
    "Freunden" : "Freund",
    "Freunde": "Freund",

    "Fremdwährungsbetrages" : "Fremdwährungsbetrag",
    "Gegenkontos" : "Gegenkonto",
    "Gegenkonten": "Gegenkonto",
    "Gehaltsbescheinigungen" : "Gehaltsbescheinigung",
    "Gehaltseingänge" : "Gehaltseingang",
    "Gehaltseingangs": "Gehaltseingang",
    "Gehaltskontos" : "Gehaltskonto",
    "Gehaltskonten": "Gehaltskonto",
    "Gehaltsnachweise" : "Gehaltsnachweis",
    "Gehaltsnachweises": "Gehaltsnachweis",
    "Gehaltsnachweisen": "Gehaltsnachweis",
    "Geht" : "gehen",
    "Geldanlagen ": "Geldanlage",
    "Geldautomaten" : "Geldautomat",
    "Geldbetrages": "Geldbetrag",
    "Geldeingangs" : "Geldeingang",
    "Geldeingänge" : "Geldeingang",
    "Geldeingängen": "Geldeingang",
    "Gemeinschaftsfreistellungsauftrages" : "Gemeinschaftsfreistellungsauftrag",
    "Gemeinschaftskonten" : "Gemeinschaftskonto",
    "Gemeinschaftskontos" : "Gemeinschaftskonto",
    "Gemeinschaftkontos" : "Gemeinschaftkonto",
    "Genossenschaftsbanken" : "Genossenschaftsbank",
    "geografischen" : "geografisch",
    "geografischer": "geografisch",
    "geografischem": "geografisch",
    "geografischen": "geografisch",
    "geografisches": "geografisch",

    "Gerichtsurteile": "Gerichtsurteil",
    "Gerichtsurteilen": "Gerichtsurteil",
    "Gerichtsurteils": "Gerichtsurteil",

    "Geschäftsanteile" : "Geschäftsanteil",
    "Geschäftsanteilen": "Geschäftsanteil",
    "Geschäftsanteils": "Geschäftsanteil",
    "Geschäftsjahres" : "Geschäftsjahr",
    "Geschäftsjahre": "Geschäftsjahr",
    "Geschäftsjahren": "Geschäftsjahr",

    "Geschäftskontos" : "Geschäftskonto",
    "Geschäftskonten" : "Geschäftskonto",
    "Geschäftskredite" : "Geschäftskredit",
    "Geschäftskrediten": "Geschäftskredit",

    "Geschäftskunden" : "Geschäftskunde",
    "Geschäftspartnern" : "Geschäftspartner",
    "Geschäftstages" : "Geschäftstag",
    "Geschäftstage": "Geschäftstag",
    "Geschäftstagen": "Geschäftstag",
    "Gibt" : "geben",
    "Girobriefumschläge" : "Girobriefumschlag",
    "Girokontos" : "Girokonto",
    "Girokonten": "Girokonto",
    "Gläubigers" : "Gläubiger",
    "Gutschriften" : "Gutschrift",
    "grundsätzliche" : "grundsätzlich",
    "grundsätzlicher": "grundsätzlich",
    "grundsätzliches": "grundsätzlich",
    "grundsätzlichem": "grundsätzlich",
    "grundsätzlichen": "grundsätzlich",

    "Gültiges" : "gültig",
    "Handynummern" : "Handynummer",
    "Handys" : "Handy",
    "Hat" : "haben",
    "HBCI-Verfahrens": "HBCI-Verfahren",
    "Höchstbetrages" : "Höchstbetrag",
    "ID-Verfahrens" : "ID-Verfahren",
    "Inlandsüberweisungen" : "Inlandsüberweisung",
    "Jahresgebühren" : "Jahresgebühr",
    "Jahrzinses": "Jahrzins",
    "Jahrzinse": "Jahrzins",
    "Jahrzinsen": "Jahrzins",
    "Kann"  : "können",
    "Kapitalerträgen" : "Kapitalertrag",
    "Kapitalerträge": "Kapitalertrag",

    "Kommt" : "kommen",
    "Kontoverbindungen" : "Kontoverbindung",
    "Kreditnehmers" : "Kreditnehmer",
    "Halbjahreskontoauszugs" : "Halbjahreskontoauszug",
    "Halbjahreskontoauszüge": "Halbjahreskontoauszug",
    "Halbjahreskontoauszügen": "Halbjahreskontoauszug",
    "individuelle" : "individuell",
    "individuelles": "individuell",
    "individueller": "individuell",
    "individuellen": "individuell",
    "individuellem": "individuell",
    "inländische": "inländisch",
    "inländischer": "inländisch",
    "inländisches": "inländisch",
    "inländischem": "inländisch",
    "inländischen": "inländisch",
    "Inhaberschuldverschreibungen" : "Inhaberschuldverschreibung",
    "Inlandsüberweisungen": "Inlandsüberweisung",
    "Insolvenzverfahrens" : "Insolvenzverfahren",
    "Internetbrowsern" : "Internetbrowser",
    
    "Internetzahlungen" : "Internetzahlung",
    "Internetseiten" : "Internetseite",
    "Internetseites": "Internetseite",
    "Investmentgesellschaften" : "Investmentgesellschaft",
    "Jahresabschlüsse" : "Jahresabschluss",
    "Jahresabschlüssen": "Jahresabschluss",
    "Jahresabschlusses": "Jahresabschluss",
    "Jugendfestgeldkontos": "Jugendfestgeldkonto",
    "Jugendfestgeldkonten": "Jugendfestgeldkonto",
    "Jugendtagesgeldkontos": "Jugendtagesgeldkonto",
    "Jugendtagesgeldkonten": "Jugendtagesgeldkonto",
    "karten" : "Karte",
    "Kalendarjahres": "Kalendarjahr",
    "Kalendarjahre": "Kalendarjahr",
    "Kalendarmonates": "Kalendarmonat",
    "Kalendarmonate": "Kalendarmonat",
    "Kalendarmonats": "Kalendarmonat",

    "Karten" : "Karte",
    "Kassenterminals" : "kassenterminal",
    "Kalendermonats" : "Kalendermonat",
    "Karten" : "Karte",
    "Kapitalerträge" : "Kapitalertrag",
    "Kaufpreises" : "Kaufpreis",
    "Kaufvorgangs": "Kaufvorgang",
    "Kaufvorganges": "Kaufvorgang",
    "Kaufvorgänge": "Kaufvorgang",
    "Kaufvorgängen": "Kaufvorgang",

    "Kartenantrags" : "Kartenantrag",
    "Kartenantrages": "Kartenantrag",
    "Kartenanträge": "Kartenantrag",
    "Kartenanträgen": "Kartenantrag",
    "Kartenumsätze": "Kartenumsatz",
    "Kartenumsätzen": "Kartenumsatz",
    "Kartenumsatzes": "Kartenumsatz",
    "Kartenzahlungen" : "Kartenzahlung",
    "Kirchensteuersatzes": "Kirchensteuersatz",
    "Kirchensteuersätze": "Kirchensteuersatz",
    "Kirchensteuersätzen": "Kirchensteuersatz",
    "Kontaktlos" : "kontaktlos",
    "Kontaktlose": "kontaktlos",
    "Kontaktlosen": "kontaktlos",
    "Kontaktloses": "kontaktlos",
    "Kontaktloser": "kontaktlos",
    "Kontaktlosem": "kontaktlos",
    "kontaktlose": "kontaktlos",
    "kontaktlosen" : "kontaktlos",
    "kontaktloses" : "kontaktlos",
    "kontaktloser": "kontaktlos",
    "kontaktlosem": "kontaktlos",
    "Kontoinhabers": "Kontoinhaber",
    "Kontoinhabern": "Kontoinhaber",
    "Kontozuganges" : "Kontozugang",
    "Kontozugangs": "Kontozugang",
    "Kontozugänge": "Kontozugang",
    "Kontozugängen": "Kontozugang",
    "Kreditantrags": "Kreditantrag",
    "Kreditantrages": "Kreditantrag",
    "Kreditanträge": "Kreditantrag",
    "Kreditanträgen": "Kreditantrag",
    "kryptografischen" : "kryptografisch",
    "kryptografische": "kryptografisch",
    "kryptografisches": "kryptografisch",
    "kryptografischer": "kryptografisch",
    "kryptografischem": "kryptografisch",
    "Kapitalerträge" : "Kapitalertrag",
    "Kapitalerträgen": "Kapitalertrag",

    "Kapitalertragsteuerverfahrens" :         "Kapitalertragsteuerverfahren",
    "Kontonamen" : "Kontoname",
    "Kontos" : "Konto",
    "Konten": "Konto",
    "Kontoauszuges" : "Kontoauszug",
    "Kontoauszüge" : "Kontoauszug",
    "Kontoauszügen": "Kontoauszug",
    "Kontoeröffnungsprozesse" :"Kontoeröffnungsprozess",
    "Kontoführungsgebühren" : "Kontoführungsgebühr",
    "Kontoumsätze": "Kontoumsatz",
    "Kontoumsätzen": "Kontoumsatz",
    "Kontoumsatzes": "Kontoumsatz",

    "Kreditanfragen" : "Kreditanfrage",
    "Kreditbetrages" : "Kreditbetrag",
    "Kreditbetrags": "Kreditbetrag",
    "Kreditbeträge": "Kreditbetrag",
    "Kreditgebers" : "Kreditgeber",
    "Kreditinstituts" : "Kreditinstitut",
    "Kreditinstitute": "Kreditinstitut",
    "Kreditinstituten": "Kreditinstitut",
    "Kreditkarten" : "Kreditkarte",
    "Kreditkartenkontos" : "Kreditkartenkonto",
    "Kreditkartenkonten": "Kreditkartenkonto",
    "Kreditkartentransaktionen" :"Kreditkartentransaktion",
    "Kreditkartenumsätze": "Kreditkartenumsatz",
    "Kreditkartenumsätzen": "Kreditkartenumsatz",
    "Kreditkartenumsatzes": "Kreditkartenumsatz",

    "Kreditkartenzahlungen" : "Kreditkartenzahlung",
    "Kreditkontos" : "Kreditkonto",
    "Kreditkonten": "Kreditkonto",
    "Kreditnehmers" : "Kreditnehmer",
    "Kreditverträge": "Kreditvertrag",
    "Kreditverträgen": "Kreditvertrag",
    "Kreditvertrages": "Kreditvertrag",
    "Kreditvertrags": "Kreditvertrag",
    "Kreditzinsen" : "Kreditzins",
    "Kreditzinses": "Kreditzins",

    "Kreditrückzahlungen" : "Kreditrückzahlung",
    "Kursrückgänge" : "Kursrückgang",
    "Kursrückgängen": "Kursrückgang",
    "Kursrückganges": "Kursrückgang",
    "Kursrückgangs": "Kursrückgang",
    "Kurzmitteilungen" : "Kurzmitteilung",
    "Kundenservices" : "Kundenservice",
    "Lehne" : "lehnen",
    "Lastschriften" : "Lastschrift",
    "Lastschriftmandate"  : "Lastschriftmandat",
    "Lastschriftmandats": "Lastschriftmandat",

    "Leuchtfeldes" : "Leuchtfeld",
    "Leuchtfelder": "Leuchtfeld",
    "Leuchtfeldern": "Leuchtfeld",

    "Leitzinses" : "Leitzins",
    "Leitzinse": "Leitzins",
    "Leitzinsen": "Leitzins",

    "Lastschriftverfahrens" : "Lastschriftverfahren",
    "Leasingverträge": "Leasingvertrag",
    "Leasingverträgen": "Leasingvertrag",
    "Leasingvertrages": "Leasingvertrag",
    "Leasingvertrags": "Leasingvertrag",
    "marktüblichen": "marktüblich",
    "marktüblichem": "marktüblich",
    "marktüblicher": "marktüblich",
    "marktübliches": "marktüblich",
    "marktübliche": "marktüblich",
    "Marktzinsen": "Marktzins",
    "Marktzinses": "Marktzins",
    "Marktzinse": "Marktzins",
    "Marktzinssatzes": "Marktzinssatz",
    "Marktzinssätze": "Marktzinssatz",
    "Marktzinssätzen": "Marktzinssatz",
    "Mietkautionsbürgschaften" : "Mietkautionsbürgschaft",
    "Mietkautionskonten" : "Mietkautionskonto",
    "Mietkautionskontos": "Mietkautionskonto",

    "Mietverhältnisses" : "Mietverhältnis",
    "Mietverhältnisse": "Mietverhältnis",
    "Motiv-karten" : "Motiv-karte",
    "Minderjährige" : "minderjährig",
    "Minderjährigen": "minderjährig",
    "Minderjähriges": "minderjährig",
    "Minderjähriger": "minderjährig",
    "minderjährige": "minderjährig",
    "minderjährigen": "minderjährig",
    "minderjähriges": "minderjährig",
    "minderjähriger": "minderjährig",
    "minderjährigem": "minderjährig",
    "Minderjährigenkontos" : "Minderjährigenkonto",
    "Minderjährigenkonten": "Minderjährigenkonto",
    "Mindestbetrages" : "Mindestbetrag",
    "Mindestbetrags": "Mindestbetrag",
    "missbräuchlichen" : "missbräuchlich",
    "missbräuchliche": "missbräuchlich",
    "missbräuchlicher": "missbräuchlich",
    "missbräuchliches": "missbräuchlich",
    "missbräuchlichem": "missbräuchlich",

    "Mitgliedschaftsanteilen" : "Mitgliedschaftsanteil",
    "Mitgliedschaftsanteile": "Mitgliedschaftsanteil",
    "Mobilfunkvertrages" : "Mobilfunkvertrag",
    "Mobilfunkvertrags" : "Mobilfunkvertrag",
    "Mobilgeräte" : "Mobilgerät",
    "Mobilgeräten": "Mobilgerät",
    "Mobilgerätes": "Mobilgerät",

    "mobileTAN-Verfahrens" : "mobileTAN-Verfahren",
    "mobileTAN-Vorgänge" :"mobileTAN-Vorgang",
    "mobileTAN-Vorgängen": "mobileTAN-Vorgang",
    "Mobilfunkanbietern": "Mobilfunkanbieter",
    "Mobilfunkanbieters" : "Mobilfunkanbieter",
    "Monate" : "Monat",
    "Monatseingänge" :"Monatseingang",
    "Monatseingängen": "Monatseingang",
    "Muss" : "müssen",
    "mTan" : "mTAN",
    "MTan": "mTAN",
    "mTAN-Verfahrens" : "mTAN-Verfahren",
    "Online-Banking-Zugangs" : "Online-Banking-Zugang",
    "Online-Bankings" : "Online-Banking",
    "Nachfinanzierungen" : "Nachfinanzierung",
    "Nachforschungsantrages" : "Nachforschungsantrag",
    "Nachforschungsanträge": "Nachforschungsantrag",

    "Nachforschungsantrags" : "Nachforschungsantrag",
    "Nachrangfinanzierungen" : "Nachrangfinanzierung",
    "Nettodarlehensbeträgen": "Nettodarlehensbetrag",
    "Nettodarlehensbeträge": "Nettodarlehensbetrag",
    "Nettodarlehensbetrags": "Nettodarlehensbetrag",
    "Nettodarlehensbetrages": "Nettodarlehensbetrag",
    "neue" : "neu",
    "neues": "neu",
    "neuer": "neu",
    "neuem": "neu",
    "neuen": "neu",
    "Neue": "neu",
    "Neues": "neu",
    "Neuer": "neu",
    "Neuem": "neu",
    "Neuen": "neu",

    "Neuemissionen" : "Neuemission",
    "Oderkontos": "Oderkonto",
    "Oderkonten": "Oderkonto",
    "Oder-kontos": "Oderkonto",
    "Oder-konto": "Oderkonto",

    "Oder-konten": "Oderkonto",
    "Online-Einkäufe" : "Online-Einkauf",
    "onlinefähiges" : "onlinefähig",
    "onlinefähige": "onlinefähig",
    "onlinefähiger": "onlinefähig",
    "onlinefähigen": "onlinefähig",
    "onlinefähigem": "onlinefähig",
    "Online-Kredite" : "Online-Kredit",
    "Online-Kredits": "Online-Kredit",
    "Online-Krediten": "Online-Kredit",

    "Online-Dauerauftrages" : "Online-Dauerauftrag",
    "Online-Dauerauftrags": "Online-Dauerauftrag",
    "Online-Daueraufträge": "Online-Dauerauftrag",
    "Online-Daueraufträgen": "Online-Dauerauftrag",
    "Online-Überweisungen" : "Online-Überweisung",
    "Optionsscheine" : "Optionsschein",
    "Orders" : "Order",
    "Passwörtern" : "Passwort",
    "Passwörter": "Passwort",
    "Passwortes": "Passwort",
    "Pensionseingängen" : "Pensionseingang",
    "Pensionseingänge": "Pensionseingang",
    "Pensionseingangs": "Pensionseingang",
    "Pensionseinganges": "Pensionseingang",

    "Personalausweises" : "Personalausweis",

    "Personalausweise" : "Personalausweis",
    "personenbezogene" : "personenbezogen",
    "personenbezogener": "personenbezogen",
    "personenbezogenes": "personenbezogen",
    "personenbezogenen": "personenbezogen",
    "personenbezogenem": "personenbezogen",

    "Personen" : "Person",
    "pfändungsfreie" : "pfändungsfrei",
    "pfändungsfreies": "pfändungsfrei",
    "pfändungsfreier": "pfändungsfrei",
    "pfändungsfreien": "pfändungsfrei",
    "pfändungsfreiem": "pfändungsfrei",

    "photoTAN-Verfahrens" : "photoTAN-Verfahren",
    "P-Kontos" : "P-Konto",
    "P-Konten": "P-Konto",

    "Posteineingangs": "Posteineingang",
    "Posteineinganges": "Posteineingang",
    "Posteineingänge": "Posteineingang",
    "Posteineingängen": "Posteineingang",

    "Postfachs" : "Postfach",
    "POSTIDENT" : "PostIdent",
    "Produktangeboten" : "Produktangebot",
    "Produktangebotes": "Produktangebot",
    "Produktangebote" : "Produktangebot",
    "Prepaid-Karten" : "Prepaid-Karte",
    "Prepaid-Kreditkarten" : "Prepaid-Kreditkarte",
    "Privatkontos" : "Privatkonto",
    "Privatkonten": "Privatkonto",
    "Privatpersonen" : "Privateperson",
    "Push-Mitteilungen" : "Push-Mitteilung",

    "pushTAN-Verfahrens" : "pushTAN-Verfahren",
    "Rahmenkredite": "Rahmenkredit",
    "Rahmenkrediten": "Rahmenkredit",
    "Rahmenkredites": "Rahmenkredit",
    "Rahmenkredits": "Rahmenkredit",
    "Ratenkredite" : "Ratenkredit",
    "Ratenkrediten": "Ratenkredit",
    "Ratenkredites" : "Ratenkredit",
    "Ratenkredits" : "Ratenkredit",
    "Ratenzahlungen" : "Ratenzahlung",
    "Rechnungsabschlüsse" : "Rechnungsabschluss",
    "Rechnungsabschlüssen": "Rechnungsabschluss",

    "Rechnungsabschlusses": "Rechnungsabschluss",
    "Referenzkontos" : "Referenzkonto",
    "Referenzkonten" : "Referenzkonto",
    "Referenzzinssatzes": "Referenzzinssatz",
    "Referenzzinssätze": "Referenzzinssatz",
    "Referenzzinssätzen": "Referenzzinssatz",
    "Registrierungsvorganges": "Registrierungsvorgang",
    "Registrierungsvorgangs": "Registrierungsvorgang",
    "Registrierungsvorgänge": "Registrierungsvorgang",
    "Registrierungsvorgängen": "Registrierungsvorgang",
    "Reichen" : "reichen",
    "Reiche": "reichen",
    "Reisepasses" : "Reisepass",
    "Reisepässe": "Reisepass",
    "Renteneingängen" : "Renteneingang",
    "Renteneingänge": "Renteneingang",
    "Renteneinganges": "Renteneingang",
    "Renteneingangs": "Renteneingang",
    "richtige": "richtig",
    "Ruf" : "rufen",

    "Sammelaufträge": "Sammelauftrag",
    "Sammelaufträgen": "Sammelauftrag",
    "Sammelauftrags": "Sammelauftrag",
    "Sammelaufträges": "Sammelauftrag",
    "SCHUFA" : "Schufa",
    "Schufaeintrages" : " Schufaeintrag",
    "Schufaeinträge": " Schufaeintrag",
    "Schufaeinträgen": " Schufaeintrag",

    "Schufaeintrags": " Schufaeintrag",
    "Secure-Verfahrens" : "Secure-Verfahren",
    "Selbstauskünfte" :"Selbstauskunft",
    "Selbstauskünften": "Selbstauskunft",
    "selbständige": "selbständig",
    "selbständiges": "selbständig",
    "selbständiger": "selbständig",
    "selbständigem": "selbständig",
    "selbständigen": "selbständig",
    "SEPA-Lastschriften" : "SEPA-Lastschrift",
    "SEPA-Mandate" : "SEPA-Mandat",

    "SEPA-Sammelaufträge" : "SEPA-Sammelauftrag",
    "SEPA-Sammelaufträgen": "SEPA-Sammelauftrag",
    "SEPA-Sammelauftrags": "SEPA-Sammelauftrag",
    "SEPA-Sammelaufträges": "SEPA-Sammelauftrag",

    "Shops" : "Shop",
    "Scheckeinreichungen" : "Scheckeinreichung",
    "Schlüsseln" : "Schlüssel",
    "Schuldverschreibungen" : "Schuldverschreibung",
    "Sicherheitsgründen" : "Sicherheitsgrund" ,
    "Sicherheitsverfahrens": "Sicherheitsverfahren",
    "Sicherheitsstandards" : "Sicherheitsstandard",
    "Sicherheits-Schlüsseln" : "Sicherheits-Schlüssel",
    "smsTAN-Vertrages" : "smsTAN-Vertrag",
    "smsTAN-Vertrags" : "smsTAN-Vertrag",
    "Sicherheitsniveaus" : "Sicherheitsniveau",
    "Sicherungssysteme" : "Sicherungssystem",
    "Sicherungssystemen": "Sicherungssystem",
    "Sichteinlagen" : "Sichteinlage",

    "Sondertilgungen" : "Sondertilgung",
    "Sonderzahlungen" : "Sonderzahlung",
    "Sollten" : "sollen",
    "Sollzinsen" : "Sollzins",
    "Sollzinses": "Sollzins",
    "Sollzinse": "Sollzins",
    "Sollzinssatzes": "Sollzinssatz",
    "Sollzinssätze": "Sollzinssatz",
    "Sollzinssätzen": "Sollzinssatz",
    "Sonderleistungen" : "Sonderleistung",
    "Sparer-Pauschbetrag" : "Sparer-Pauschbetrag",
    "Sparbeträge": "Sparbetrag",
    "Sparbeträgen": "Sparbetrag",
    "Sparbetrages": "Sparbetrag",
    "Sparbetrags": "Sparbetrag",
    "Spareinlagen" : "Spareinlage",
    "Sparkontos" : "Sparkonto",
    "Sparkonten" : "Sparkonto",
    "Spar-kontos": "Sparkonto",
    "Spar-konto": "Sparkonto",

    "Spar-konten": "Sparkonto",
    "Sparverträge" : "Sparvertrag",
    "Sparverträgen": "Sparvertrag",
    "Sparvertrages" : "Sparvertrag",
    "Sparvertrags" : "Sparvertrag",
    "Sparziele" : "Sparziel",
    "Sparzielen" : "Sparziel",
    "Sparzieles": "Sparziel",
    "Sperr-Notrufnummern" : "Sperr-Notrufnummer",
    "Smartphones" : "Smartphone", 
    "Standardkredite": "Standardkredit",
    "Standardkrediten": "Standardkredit",
    "Steigt" : "steigen",
    "Steuerbescheide" : "Steuerbescheid",
    "Steuerbescheiden": "Steuerbescheid",
    "Steuerbescheides": "Steuerbescheid",
    "Steursatzes": "Steursatz",
    "Steursätze": "Steursatz",
    "Steursätzen": "Steursatz",
    "Stimmt" : "stimmen",

    "stimmt" : "stimmen",
    "Tablets" : "Tablet",
    "TAN-Generatoren" : "TAN-Generator",
    "TAN-Generatore": "TAN-Generator",

    "TAN-Verfahrens" : "TAN-Verfahren",
    "TANs" : "TAN",
    "TAN-pflichtiger" : "TAN-pflichtig",
    "TAN-pflichtiges": "TAN-pflichtig",
    "TAN-pflichtigem": "TAN-pflichtig",
    "TAN-pflichtige": "TAN-pflichtig",
    "TAN-pflichtigen": "TAN-pflichtig",

    "tagesaktuellen" : "tagesaktuell",
    "tagesaktuelles": "tagesaktuell",
    "tagesaktuelle": "tagesaktuell",
    "tagesaktueller": "tagesaktuell",
    "tagesaktuellem": "tagesaktuell",
    "Tages" : "Tag",
    "Tagesgeldkontos" : "Tagesgeldkonto",
    "Tagesgeldkonten": "Tagesgeldkonto",
    "Tagesgeld-konto": "Tagesgeldkonto",
    "Tagesgeld-kontos": "Tagesgeldkonto",
    "Tagesgeld-konten": "Tagesgeldkonto",
    "Teilbeträgen" : "Teilbetrag",
    "Teilbeträge": "Teilbetrag",
    "Teilbetrags": "Teilbetrag",
    "Teilbetrages": "Teilbetrag",

    "Teilbuchungen" : "Teilbuchung",
    "Teilrückzahlungen" : "Teilrückzahlung",
    "Telefon-Bankings" : "Telefon-Banking",
    "Telefonnummern" : "Telefonnummer",
    "Terminals" : "Terminal",
    "Terminauftrages" : "Terminauftrag",
    "Terminauftrags": "Terminauftrag",
    "Terminaufträge" : "Terminauftrag",
    "Terminaufträgen": "Terminauftrag",
    "Terminkontos" : "Terminkonto",
    "Terminkonten": "Terminkonto",
    "Tilgungen" : "Tilgung",
    "Transaktionen": "Transaktion",
    "Transaktionsnummern" : "Transaktionsnummer",
    "Turbos" : "Turbo",
    "Überweisungsbetrages" : "Überweisungsbetrag",
    "Überweisungsbetrags": "Überweisungsbetrag",
    "Überweisungen" : "Überweisung",
    "Überweisungslimits" : "Überweisungslimit",
    "Überweisungsvorlagen" : "Überweisungsvorlage",
    "umfangreichen" : "umfangreich",
    "umfangreiches": "umfangreich",
    "umfangreiche": "umfangreich",
    "umfangreicher": "umfangreich",
    "umfangreichem": "umfangreich",
    "Umsätze" : "Umsatz",
    "Umsätzen": "Umsatz",
    "unselbstständigen" :"unselbstständig",
    "unselbstständiger": "unselbstständig",
    "unselbstständiges": "unselbstständig",
    "unselbstständige": "unselbstständig",
    "unselbstständigem": "unselbstständig",
    "Unternehmenskontos" : "Unternehmenskonto",
    "Unternehmenskonten": "Unternehmenskonto",
    "Unterkontos" : "Unterkonto",
    "Unterkonten": "Unterkonto",
    "Textnachrichten" : "Textnachricht",
    "vereinbarte" : "vereinbart",
    "vereinbartes": "vereinbart",
    "vereinbarter": "vereinbart",
    "vereinbartem": "vereinbart",
    "vereinbarten": "vereinbart",
    "verfügt" : "verfügen",


    "Verbraucherinsolvenzverfahrens": "Verbraucherinsolvenzverfahren",
    "Verrechnungskontos" : "Verrechnungskonto",
    "Verrechnungskonten" : "Verrechnungskonto",
    "Vertrages" : "Vertrag",
    "Vertrags": "Vertrag",
    "Videoident-Verfahrens" : "Videoident-Verfahren",
    "Verpfändungen" : "Verpfändung",
    "Verschlüsselungsverfahrens" : "Verschlüsselungsverfahren",
    "Volljährige": "volljährig",
    "Volljährigen": "volljährig",
    "Volljähriges": "volljährig",
    "Volljähriger": "volljährig",
    "volljährige": "volljährig",
    "volljährigen": "volljährig",
    "volljähriges": "volljährig",
    "volljähriger": "volljährig",
    "vollstreckbaren" : "vollstreckbar",
    "vollstreckbares": "vollstreckbar",
    "vollstreckbarem": "vollstreckbar",
    "vollstreckbarer": "vollstreckbar",
    "vollstreckbare": "vollstreckbar",

    "Voraussetzungen" : "Voraussetzung",
    "Vorschusszinsen" : "Vorschusszins",
    "Vorteils-Kontos": "Vorteilskonto",
    "Vorteils-Konten": "Vorteilskonto",
    "Vorteils-Konto": "Vorteilskonto",
    "Werktage": "Werktag",
    "Werktagen": "Werktag",
    "Werktages": "Werktag",
    "Wertpapieraufträgen": "Wertpapierauftrag",
    "Wertpapierauftrages": "Wertpapierauftrag",
    "Wertpapierauftrags": "Wertpapierauftrag",
    "Wertpapieraufträge": "Wertpapierauftrag",
    "Wertpapiere" : "Wertpapier",
    "Wertpapiers" : "Wertpapier",
    "Wertpapieren" : "Wertpapier",
    "Wertpapiergeschäfte" : "Wertpapiergeschäft",
    "Wertpapiergeschäftes": "Wertpapiergeschäft",
    "Wertpapiergeschäften" : "Wertpapiergeschäft",
    "Wertpapierkontos" : "Wertpapierkonto",
    "Wertpapierkonten": "Wertpapierkonto",
    "Wertschriftenaufträgen": "Wertschriftenauftrag",
    "Wertschriftenauftrages": "Wertschriftenauftrag",
    "Wertschriftenauftrags": "Wertschriftenauftrag",
    "Wertschriftenaufträge": "Wertschriftenauftrag",
    "Wirtschaftsraums" : "Wirtschaftsraum",
    "Wochenlimits" : "Wochenlimit",
    "Wohnungseigentümern" : "Wohnungseigentümer",
    "Wurde": "werden",
    "Zahlungsaufträgen" : "Zahlungsauftrag",
    "Zahlungsauftrages": "Zahlungsauftrag",
    "Zahlungsauftrags": "Zahlungsauftrag",
    "Zahlungsaufträge" : "Zahlungsauftrag",
    "Zahlungsdiensten" : "Zahlungsdienst",
    "Zahlungsdienste": "Zahlungsdienst",
    "Zahlungseingänge" : "Zahlungseingang",
    "Zahlungseingängen": "Zahlungseingang",
    "Zahlungseinganges": "Zahlungseingang",
    "Zahlungsempfängers" : "Zahlungsempfänger",
    "Zahlungskontos" : "Zahlungskonto",
    "Zahlungskonten": "Zahlungskonto",
    "Zahlungspartnern" : "Zahlungspartner",
    "Zahlungsvorgänge": "Zahlungsvorgang",
    "Zahlungsvorgängen": "Zahlungsvorgang",
    "Zahlungsvorganges": "Zahlungsvorgang",
    "Zinserträge" : "Zinsertrag",
    "Zinsertrags": "Zinsertrag",
    "Zinsertrages": "Zinsertrag",
    "zinsgünstiges" : "zinsgünstig",
    "zinsgünstiger": "zinsgünstig",
    "zinsgünstigen": "zinsgünstig",
    "zinsgünstige": "zinsgünstig",

    "zinsgünstigem": "zinsgünstig",
    "Zinssätze" : "Zinssatz",
    "Zinssätzen": "Zinssatz",
    "Zinssatzes": "Zinssatz",
    "Zinszahlungen" : "Zinszahlung",
    "Zinsaufschläge": "Zinsaufschlag",
    "Zinszuschläge" : "Zinszuschlag",
    "Zusatzgebühren" : "Zusatzgebühr",
    "zugesandt" : "zusenden",
    "zugestellt" : "zustellen",
    "zugeschickt": "zuschicken",
    "Zusatzkarten" : "Zusatzkarte",
    "zusätzliche": "zusätzlich"

}