CUSTOM_LOOKUP = {
    "Abrechnungskontos" : "Abrechnungskonto",
    "Abrechnungskonten": "Abrechnungskonto",
    "Abwicklungskontos" : "Abwicklungskonto",
    "Abwicklungskonten" : "Abwicklungskonto",
    "Anlagekontos" : "Anlagekonto",
    "Anlagekontne": "Anlagekonto",
    "Anmeldenamen" : "Anmeldename",
    "Auszahlungskontos" : "Auszahlungskonto",
    "Auszahlungskonten" : "Auszahlungskonto",
    "angeboten" : "anbieten",
    "Aufträge"  : "Auftrag",
    "Bankkontos" : "Bankkonto",
    "Basisgirokontos" : "Basisgirokonto",
    "Basisgirokonten": "Basisgirokonto",
    "Basiskontos" : "Basiskonto",
    "Basiskonten": "Basiskonto",
    "Daueraufträge" : "Dauerauftrag",
    "Dienstleistungen" : "Dienstleistung",
    "eingeräumt" : "einräumen",
    "Empfängerkontos" : "Empfängerkonto",
    "Empfängerkonten": "Empfängerkonto",
    "Erbscheines" : "Erbschein",
    "Erkanntes" : "erkannt",
    "Erkannter": "erkannt",
    "FlatKontos" : "FlatKonto",
    "FlatKonten": "FlatKonto",
    "Festgeldkontos" : "Festgeldkonto",
    "Festgeldkonten" : "Festgeldkonto",
    "Freistellungsauftrages" : "Freistellungsauftrag",
    "Gegenkontos" : "Gegenkonto",
    "Gegenkonten": "Gegenkonto",
    "Gehaltskontos" : "Gehaltskonto",
    "Gehaltskonten": "Gehaltskonto",
    "Geldautomaten" : "Geldautomat",
    "Gemeinschaftskonten" : "Gemeinschaftskonto",
    "Gemeinschaftskontos" : "Gemeinschaftskonto",
    "Gemeinschaftkontos" : "Gemeinschaftkonto",
    "Geschäftskontos" : "Geschäftskontos",
    "Geschäftskonten" : "Geschäftskontos",
    "Geschäftskunden" : "Geschäftskunde",
    "Girokontos" : "Girokonto",
    "Girokonten": "Girokonto",
    "Kann"  : "Können",
    "individuelle" : "individuell",
    "Internetseiten" : "Internetseite",
    "karte" : "karte",
    "Kontaktlos" : "kontaktlos",
    "kontaktlose": "kontaktlos",
    "kontaktlosen" : "kontaktlosen",
    "Kontonamen" : "Kontoname",
    "Kontos" : "Konto",
    "Konten": "Konto",
    "Kontoauszüge" : "Kontoauszug",
    "Kontoauszügen": "Kontoauszug",
    "Kreditkarten" : "Kreditkarte",
    "Kreditkartenkontos" : "Kreditkartenkonto",
    "Kreditkartenkonten": "Kreditkartenkonto",
    "Kreditkontos" : "Kreditkonto",
    "Kreditkonten": "Kreditkonto",
    "Minderjährigenkontos" : "Minderjährigenkonto",
    "Minderjährigenkonten": "Minderjährigenkonto",
    "Monate" : "Monat",
    "mTan" : "mTAN",
    "MTan": "mTAN",

    "Personen" : "Person",
    "Produktangeboten" : "Produktangebot",
    "Produktangebote" : "Produktangebot",
    "Privatkontos" : "Privatkonto",
    "Privatkonten": "Privatkonto",
    "Privatpersonen" : "Privateperson",
    "Referenzkontos" : "Referenzkonto",
    "Referenzkonten" : "Referenzkonto",
    "richtige": "richtig",
    "Sicherheitsgründen" : "Sicherheitsgrund" ,
    "Sparkontos" : "Sparkonto",
    "Sparkonten" : "Sparkonto",
    "Tagesgeldkontos" : "Tagesgeldkonto",
    "Tagesgeldkonten": "Tagesgeldkonto",
    "Terminkontos" : "Terminkonto",
    "Terminkonten": "Terminkonto",
    "Transaktionen": "Transaktion",
    "Transaktionsnummern" : "Transaktionsnummer",
    "Überweisungen" : "Überweisung",
    "Ümsätze" : "Umsatz",
    "Unternehmenskontos" : "Unternehmenskonto",
    "Unternehmenskonten": "Unternehmenskonto",
    "Unterkontos" : "Unterkonto",
    "Unterkonten": "Unterkonto",
    "vereinbarte" : "vereinbart",
    "Verrechnungskontos" : "Verrechnungskonto",
    "Verrechnungskonten" : "Verrechnungskonto",
    "Voraussetzungen" : "Voraussetzung",
    "Wertpapiere" : "Wertpapier",
    "Wertpapieren" : "Wertpapier",
    "Wertpapierkontos" : "Wertpapierkonto",
    "Wertpapierkonten": "Wertpapierkonto",
    "Zahlungskontos" : "Zahlungskonto",
    "Zahlungskonten": "Zahlungskonto",
    "zugeschickt": "zuschicken",
    "zusätzliche": "zusätzlich"

}